[package]
name = "puzzle-cube"
version = "0.1.0"
authors = ["Will Dixon <will@willd.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
